[package]
name = "nightcycle/checkbox"
description = "A checkbox ui: https://material.io/components/checkboxes"
version = "0.1.10"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
coldfusion = "nightcycle/cold-fusion@1.0.19"
isotope = "nightcycle/isotope@1.1.15"
signal = "quenty/signal@^2.0.0-canary"
maid = "quenty/maid@^2.0.1-canary"
